[tool.poetry]
name = "pypeid"
version = "0.1.0"
description = "Yet another implementation of PEiD with yara-python"
authors = ["Koh Nakagawa <tsunekou1019@gmail.com>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = "^3.6"
yara-python = "^3.11.0"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
mypy = "^0.770"
black = "^19.10b0"
pytest = "^5.4.1"
isort = "^4.3.21"
pip-licenses = "^2.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
